### ISSUE TITLE
clipPath is not supported in API below 18

### ISSUE THREAD

**Issue by SaeedMasoumi** [JcMinarro/RoundKornerLayouts#1]
Calling [canvas.clipPath](https://github.com/JcMinarro/RoundKornerLayouts/blob/master/roundkornerlayout/src/main/java/com/jcminarro/roundkornerlayout/CanvasRounder.kt#L23) with hardware acceleration is only supported in API level 18 and higher, so I think it will not work properly in API below 18

**Comment by JcMinarro** [comment]
I don't have any device with API below 18.
Do you have one?
Could you try if it works?
Do you know how could we improve it?

**Comment by SaeedMasoumi** [comment]
@JcMinarro This is how it looks like on HTC one mini (API 17)

![screenshot_2017-06-29-17-49-03](https://user-images.githubusercontent.com/6934577/27689532-b7f5aa82-5cf3-11e7-80c8-a1065fe671da.png)

**Comment by sergiandreplace** [comment]
Better use layer composition. I can do a PR tomorrow if you want

**Comment by JcMinarro** [comment]
Hi @sergiandreplace.
Thank you for the interest.
PR are always welcome 😉
