### ISSUE TITLE
Possible to set the radius only at bottom?

### ISSUE THREAD

**Issue by ih-sugumaranv** [JcMinarro/RoundKornerLayouts#12]
Hi there,
Possible to set the radius only at bottom of layout?

**Comment by JcMinarro** [comment]
Hi @ih-sugumaranv 
It is fixed with #17 
I will close the Issue when the new version is released

**Comment by JcMinarro** [comment]
New release published, version 0.4.0
You can download it [here](https://github.com/JcMinarro/RoundKornerLayouts/releases/tag/v-0.4.0) or updating your build.gradle file with the new version.
