### ISSUE TITLE
What's the reason to use this over CardView?

### ISSUE THREAD

**Issue by zunjae** [JcMinarro/RoundKornerLayouts#22]
Title

**Comment by AndroidDeveloperLB** [comment]
There is no way on CardView to set which corners to make round, and in very specific radius.

**Comment by zunjae** [comment]
You can actually use `MaterialCardView` (same thing as CardView, but Material and more up to date) and specify the corners through your styles file like this


 ```xml
  <style name="MyCardView" parent="@style/Widget.MaterialComponents.CardView">
    <item name="shapeAppearanceOverlay">@style/ShapeAppearanceOverlay.MaterialCardView.Cut</item>
  </style>

 <style name="ShapeAppearanceOverlay.MaterialCardView.Cut" parent="">
    <item name="cornerFamily">rounded</item>
    <item name="cornerSizeTopRight">8dp</item>
    <item name="cornerSizeTopLeft">8dp</item>
    <item name="cornerSizeBottomRight">0dp</item>
    <item name="cornerSizeBottomLeft">0dp</item>
  </style>
```

**Comment by AndroidDeveloperLB** [comment]
@zunjae That's not the same as setting it directly in the layout XML file.
Much easier using this library instead.
Plus, you have a choice of which layout to use, while CardView is a wrapper for the layout you'd like to use.

**Comment by zunjae** [comment]
Don't mention me. It's annoying. 

You have proven that this library is useless for **ME**. Thank you.
