### ISSUE TITLE
How to add the corner dynamically in java not add it in xml?

### ISSUE THREAD

**Issue by MinaSamirCap** [JcMinarro/RoundKornerLayouts#3]
I need to change the corner radius to make a lot of different corners with one xml..

**Comment by JcMinarro** [comment]
Hello @MinaSamirCap 
On the new version, you are able to change the corner radius dynamically.
It was implemented on #4 and you can change it with the method `setCornerRadius()`

**Comment by MinaSamirCap** [comment]
Really thanks I will test it and give you my feedback but later.
