### ISSUE TITLE
lateinit property has not been initialized kotlin

### ISSUE THREAD

**Issue by aboulfotoh** [JcMinarro/RoundKornerLayouts#5]
I'm using your library in my project but I'm writing my code in Java not Kotlin and I'm using Butterknife for binding views when I'm trying to deal with your view in my code I'm getting this error

kotlin.UninitializedPropertyAccessException: lateinit property rectF has not been initialized

so I can't use setCornerRadius() method because rectF hasn't been initialized yet how can I use it??

**Comment by JcMinarro** [comment]
Hello @aboulfotoh The problem is that the view has not been measured yet and the `rectF` used to delimit the boundary of the view hasn't been initialized.
I will try to fix it this weekend

**Comment by aboulfotoh** [comment]
all what you have to do is put the below line in your class CanvasRounder 
private var rectF: RectF  = android.graphics.RectF(0f, 0f, 0f, 0f)

and it will work fine

**Comment by JcMinarro** [comment]
Sound great, Give me a moment and I will fix it
