### ISSUE TITLE
can't import

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [JcMinarro/RoundKornerLayouts#7]
I get this:
![image](https://user-images.githubusercontent.com/5357526/32989809-27b18be6-cd26-11e7-99a1-c9c0d6393cf7.png)

**Comment by JcMinarro** [comment]
Hello @AndroidDeveloperLB 
the `BINTRAY_API_KEY` and `BINTRAY_USER` properties are used to publish the library to Bintray and, of course, they are privates. 
You can add someone to your global gradle.properties (It is in your gradle home) with the following signature:

```
# Bintray credential
BINTRAY_API_KEY=some_key
BINTRAY_USER=some_user
```

**Comment by AndroidDeveloperLB** [comment]
I don't understand. Why can't it just work out of the box?
And what do you suggest exactly to do to make it work?

**Comment by JcMinarro** [comment]
`BINTRY_API_KEY` and `BINTRAY_USER` are some properties used to publish the library to the bintray repository, to be able to download it with maven. 
Those properties are used in the build.gradle file and it is not able to find them when you are trying to synchronize the project.
To fix it you need to provide those properties, and they are declared into the `gradle.properties` file

**Comment by AndroidDeveloperLB** [comment]
Can you please fix it here instead?
It really is annoying when one imports a sample, and then need to investigate what is needed to make it work. It should be working from the start...

**Comment by JcMinarro** [comment]
Ok, I have added some default value to the gradle.properties to be able to build it without need to configure anything

**Comment by AndroidDeveloperLB** [comment]
Thank you!
